""" Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a “cow”.
For every digit the user guessed correctly in the wrong place is a “bull.”
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number."""

import random
from string import digits

def generate_goal():
  return "".join(random.choice(digits) for _ in range(4))

def compare_nums(goal,user_num):
  cows = 0
  bulls = 0
  used_indices_goal = set()
  used_indices_user = set()

  for i in range(len(goal)):
    if goal[i] == user_num[i]:
      cows += 1
      used_indices_goal.add(i)
      used_indices_user.add(i)

  for i in range(len(user_num)):
    if i not in used_indices_user:
      for j in range(len(goal)):
        if (goal[j] == user_num[i] and 
        j not in used_indices_goal and 
        i != j):
          bulls += 1
          used_indices_goal.add(j)
          break

  return cows, bulls

def format_output(cows, bulls):
  cow_text = "cow" if cows == 1 else "cows"
  bull_text = "bull" if bulls == 1 else "bulls"
  return f"{cows} {cow_text}, {bulls} {bull_text}"

    

def main():
  target_number = generate_goal()
  moves = 0
  print("Welcome to the Cows and Bulls Game!")
  print("Try to guess the 4-digit number.")

  while True:
    user_input = input("Enter a 4-digit number: ")
    if not (user_input.isdigit() and len(user_input)) == 4:
      print("Invalid input. Please enter exactly 4 digits.")
      continue
    
    moves += 1 
    cows, bulls = compare_nums(target_number, user_input)
    print(format_output(cows, bulls))

    if user_input == target_number:
      print(f"Congrats! You guessed the number in {moves} moves.")
      break

if __name__ == "__main__":
  main()